### ISSUE TITLE
Custom iL2CPP Thread il2pp_thread_attach

### ISSUE THREAD

**Issue by Rednick16** [sneakyevilSK/IL2CPP_Resolver#9] opened 2022-03-11 04:44 UTC
Hmm, the game crashes when i call some functions for example WorldToScreenPoint

but when I hook these functions they work fine any fixes for this?

**Comment by sneakyevilSK** [comment] 2022-03-11 16:08
I knew about this issue since beginning, but never bother to look futher since I have no clue why it happens and especially with different functions.
At the moment I just prefer to hook function like OnUpdate of some class or Camera render function and just do stuff there.
If you really need to do like World2Screen stuff, then you could take look at matrixes and just read them from Camera and calculate the screen position, instead calling the function.

**Comment by sneakyevilSK** [comment] 2022-05-14 20:25
Anyone who still has problem with this I need some tests on diff games as result:
```cpp
void* m_pThisThread = IL2CPP::Thread::Attach(IL2CPP::Domain::Get());
/*

Run your code here... 

*/
IL2CPP::Thread::Detach(m_pThisThread);
```

Instead creating new thread via API create it yourself and run this code in the loop so it attach and deattach.

**Comment by Rednick16** [comment] 2022-05-14 22:24
I did do this a while back and came back to it, it had no effect, I tested it on a mobile game(CriticalOps) and terraria il2cpp steam game, I read some where a dude said he fixed his crashes by calling the il2cpp_thread_attach everytime he was ready to call a Unity function, personally I don’t think this function dose anything useful.

**Comment by sneakyevilSK** [comment] 2022-05-15 07:11
Seems weird since I tried to do simple ESP by just filtering out objects by certain name and calling Camera WorldToScreen function and I got the thread error and after doing attach and doing same thing and detaching it, it didn't popup error anymore.

**Comment by kashiwazaki2** [comment] 2022-05-15 11:03
> Seems weird since I tried to do simple ESP by just filtering out objects by certain name and calling Camera WorldToScreen function and I got the thread error and after doing attach and doing same thing and detaching it, it didn't popup error anymore.

Well i tried it as you said to me and i can confirm it does work 100%, tested on Naraka BladePoint no crash/GC Collecting from unknown thread anymore so i guess this is an appropiate fix since i am doing like that on present and yei all works and the best part is i don't need the hook anymore.

**Comment by Rednick16** [comment] 2022-05-15 16:56
> Seems weird since I tried to do simple ESP by just filtering out objects by certain name and calling Camera WorldToScreen function and I got the thread error and after doing attach and doing same thing and detaching it, it didn't popup error anymore.

Well it seems to work I tested it on another game and it worked hahaha no idea what’s happening I guess this is the best way to use this attach method welp dipping thanks for all the help and the tool very helpful

**Comment by extremeblackliu** [comment] 2022-05-15 17:20
re-check the repo , added callback way to use OnUpdate

**Comment by kashiwazaki2** [comment] 2022-05-16 06:15
Thank you guys for your work, this need update looks dope.

**Comment by sneakyevilSK** [comment] 2022-05-20 12:26
Closing this because callbacks has been added and it is easier to use than threads.

**Closed by sneakyevilSK** 2022-05-20 12:26 UTC
Labels: bug, help wanted
